# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_fm_index')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_fm_index')
    _fm_index = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_fm_index', [dirname(__file__)])
        except ImportError:
            import _fm_index
            return _fm_index
        try:
            _mod = imp.load_module('_fm_index', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _fm_index = swig_import_helper()
    del swig_import_helper
else:
    import _fm_index
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _fm_index.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _fm_index.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _fm_index.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _fm_index.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _fm_index.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _fm_index.SwigPyIterator_equal(self, x)

    def copy(self):
        return _fm_index.SwigPyIterator_copy(self)

    def next(self):
        return _fm_index.SwigPyIterator_next(self)

    def __next__(self):
        return _fm_index.SwigPyIterator___next__(self)

    def previous(self):
        return _fm_index.SwigPyIterator_previous(self)

    def advance(self, n):
        return _fm_index.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _fm_index.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _fm_index.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _fm_index.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _fm_index.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _fm_index.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _fm_index.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _fm_index.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _fm_index.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _fm_index.IntVector___nonzero__(self)

    def __bool__(self):
        return _fm_index.IntVector___bool__(self)

    def __len__(self):
        return _fm_index.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _fm_index.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _fm_index.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _fm_index.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _fm_index.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _fm_index.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _fm_index.IntVector___setitem__(self, *args)

    def pop(self):
        return _fm_index.IntVector_pop(self)

    def append(self, x):
        return _fm_index.IntVector_append(self, x)

    def empty(self):
        return _fm_index.IntVector_empty(self)

    def size(self):
        return _fm_index.IntVector_size(self)

    def swap(self, v):
        return _fm_index.IntVector_swap(self, v)

    def begin(self):
        return _fm_index.IntVector_begin(self)

    def end(self):
        return _fm_index.IntVector_end(self)

    def rbegin(self):
        return _fm_index.IntVector_rbegin(self)

    def rend(self):
        return _fm_index.IntVector_rend(self)

    def clear(self):
        return _fm_index.IntVector_clear(self)

    def get_allocator(self):
        return _fm_index.IntVector_get_allocator(self)

    def pop_back(self):
        return _fm_index.IntVector_pop_back(self)

    def erase(self, *args):
        return _fm_index.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _fm_index.new_IntVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _fm_index.IntVector_push_back(self, x)

    def front(self):
        return _fm_index.IntVector_front(self)

    def back(self):
        return _fm_index.IntVector_back(self)

    def assign(self, n, x):
        return _fm_index.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _fm_index.IntVector_resize(self, *args)

    def insert(self, *args):
        return _fm_index.IntVector_insert(self, *args)

    def reserve(self, n):
        return _fm_index.IntVector_reserve(self, n)

    def capacity(self):
        return _fm_index.IntVector_capacity(self)
    __swig_destroy__ = _fm_index.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _fm_index.IntVector_swigregister
IntVector_swigregister(IntVector)

class IntVectorVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVectorVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVectorVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _fm_index.IntVectorVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _fm_index.IntVectorVector___nonzero__(self)

    def __bool__(self):
        return _fm_index.IntVectorVector___bool__(self)

    def __len__(self):
        return _fm_index.IntVectorVector___len__(self)

    def __getslice__(self, i, j):
        return _fm_index.IntVectorVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _fm_index.IntVectorVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _fm_index.IntVectorVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _fm_index.IntVectorVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _fm_index.IntVectorVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _fm_index.IntVectorVector___setitem__(self, *args)

    def pop(self):
        return _fm_index.IntVectorVector_pop(self)

    def append(self, x):
        return _fm_index.IntVectorVector_append(self, x)

    def empty(self):
        return _fm_index.IntVectorVector_empty(self)

    def size(self):
        return _fm_index.IntVectorVector_size(self)

    def swap(self, v):
        return _fm_index.IntVectorVector_swap(self, v)

    def begin(self):
        return _fm_index.IntVectorVector_begin(self)

    def end(self):
        return _fm_index.IntVectorVector_end(self)

    def rbegin(self):
        return _fm_index.IntVectorVector_rbegin(self)

    def rend(self):
        return _fm_index.IntVectorVector_rend(self)

    def clear(self):
        return _fm_index.IntVectorVector_clear(self)

    def get_allocator(self):
        return _fm_index.IntVectorVector_get_allocator(self)

    def pop_back(self):
        return _fm_index.IntVectorVector_pop_back(self)

    def erase(self, *args):
        return _fm_index.IntVectorVector_erase(self, *args)

    def __init__(self, *args):
        this = _fm_index.new_IntVectorVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _fm_index.IntVectorVector_push_back(self, x)

    def front(self):
        return _fm_index.IntVectorVector_front(self)

    def back(self):
        return _fm_index.IntVectorVector_back(self)

    def assign(self, n, x):
        return _fm_index.IntVectorVector_assign(self, n, x)

    def resize(self, *args):
        return _fm_index.IntVectorVector_resize(self, *args)

    def insert(self, *args):
        return _fm_index.IntVectorVector_insert(self, *args)

    def reserve(self, n):
        return _fm_index.IntVectorVector_reserve(self, n)

    def capacity(self):
        return _fm_index.IntVectorVector_capacity(self)
    __swig_destroy__ = _fm_index.delete_IntVectorVector
    __del__ = lambda self: None
IntVectorVector_swigregister = _fm_index.IntVectorVector_swigregister
IntVectorVector_swigregister(IntVectorVector)

class FMIndex(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FMIndex, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FMIndex, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _fm_index.new_FMIndex()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _fm_index.delete_FMIndex
    __del__ = lambda self: None

    def initialize(self, data):
        return _fm_index.FMIndex_initialize(self, data)

    def initialize_from_file(self, file, width):
        return _fm_index.FMIndex_initialize_from_file(self, file, width)

    def backward_search_multi(self, query):
        return _fm_index.FMIndex_backward_search_multi(self, query)

    def backward_search_step(self, symbol, low, high):
        return _fm_index.FMIndex_backward_search_step(self, symbol, low, high)

    def distinct(self, low, high):
        return _fm_index.FMIndex_distinct(self, low, high)

    def distinct_count(self, low, high):
        return _fm_index.FMIndex_distinct_count(self, low, high)

    def distinct_count_multi(self, lows, highs):
        return _fm_index.FMIndex_distinct_count_multi(self, lows, highs)

    def size(self):
        return _fm_index.FMIndex_size(self)

    def locate(self, row):
        return _fm_index.FMIndex_locate(self, row)

    def extract_text(self, begin, end):
        return _fm_index.FMIndex_extract_text(self, begin, end)

    def save(self, path):
        return _fm_index.FMIndex_save(self, path)
    __swig_setmethods__["index"] = _fm_index.FMIndex_index_set
    __swig_getmethods__["index"] = _fm_index.FMIndex_index_get
    if _newclass:
        index = _swig_property(_fm_index.FMIndex_index_get, _fm_index.FMIndex_index_set)
    __swig_setmethods__["chars"] = _fm_index.FMIndex_chars_set
    __swig_getmethods__["chars"] = _fm_index.FMIndex_chars_get
    if _newclass:
        chars = _swig_property(_fm_index.FMIndex_chars_get, _fm_index.FMIndex_chars_set)
    __swig_setmethods__["rank_c_i"] = _fm_index.FMIndex_rank_c_i_set
    __swig_getmethods__["rank_c_i"] = _fm_index.FMIndex_rank_c_i_get
    if _newclass:
        rank_c_i = _swig_property(_fm_index.FMIndex_rank_c_i_get, _fm_index.FMIndex_rank_c_i_set)
    __swig_setmethods__["rank_c_j"] = _fm_index.FMIndex_rank_c_j_set
    __swig_getmethods__["rank_c_j"] = _fm_index.FMIndex_rank_c_j_get
    if _newclass:
        rank_c_j = _swig_property(_fm_index.FMIndex_rank_c_j_get, _fm_index.FMIndex_rank_c_j_set)
FMIndex_swigregister = _fm_index.FMIndex_swigregister
FMIndex_swigregister(FMIndex)


def load_FMIndex(path):
    return _fm_index.load_FMIndex(path)
load_FMIndex = _fm_index.load_FMIndex
# This file is compatible with both classic and new-style classes.


